"""Attendance routers (design §3, §7, §2B).

Every route is gated by ``require_permission(module, action)`` from Phase 0.
CRUD shape is generated by ``_make_crud_router`` (mirrors app/employee/routes.py);
DTR creation/update use dedicated handlers that run the calc core and set the
server-authoritative actor. DTR adjustments add an approval state machine.
"""

from typing import Any

from fastapi import APIRouter, Depends, HTTPException

from app.attendance import adjustment_schemas as adj_s
from app.attendance import schemas as s
from app.attendance.adjustment_models import DtrAdjustment
from app.attendance.adjustment_services import (
    approve_adjustment,
    create_adjustment,
    get_adjustment,
    reject_adjustment,
)
from app.attendance.models import DailyTimeRecord, Shift
from app.attendance.selectors import get_active_by_id, get_list
from app.attendance.services import (
    create_dtr,
    set_overtime_approved,
    soft_delete_obj,
    update_dtr,
)
from app.common.dependencies import CurrentUser, SessionDep
from app.common.schemas import Message
from app.rbac.dependencies import require_permission

Type = type


def _make_crud_router(
    *,
    prefix: str,
    tag: str,
    module: str,
    model: Type,
    create: Type,
    update: Type,
    public: Type,
    listing: Type,
    custom_delete: bool = False,
) -> APIRouter:
    router = APIRouter(prefix=prefix, tags=[tag])
    model_name = model.__name__

    @router.get(
        "/",
        response_model=listing,
        dependencies=[Depends(require_permission(module, "view"))],
    )
    def list_objs(session: SessionDep, skip: int = 0, limit: int = 100) -> Any:
        rows, count = get_list(session=session, model=model, skip=skip, limit=limit)
        return listing(data=[public.model_validate(r) for r in rows], count=count)

    @router.get(
        "/{obj_id}",
        response_model=public,
        dependencies=[Depends(require_permission(module, "view"))],
    )
    def read_obj(session: SessionDep, obj_id) -> Any:
        db_obj = get_active_by_id(session=session, model=model, obj_id=obj_id)
        if db_obj is None:
            raise HTTPException(status_code=404, detail=f"{model_name} not found")
        return public.model_validate(db_obj)

    @router.post(
        "/",
        response_model=public,
        status_code=201,
        dependencies=[Depends(require_permission(module, "add"))],
    )
    def create_route(*, session: SessionDep, obj_in: create) -> Any:
        from app.attendance.services import create_obj

        db_obj = create_obj(session=session, model=model, data=obj_in)
        return public.model_validate(db_obj)

    @router.patch(
        "/{obj_id}",
        response_model=public,
        dependencies=[Depends(require_permission(module, "edit"))],
    )
    def update_route(*, session: SessionDep, obj_id, obj_in: update) -> Any:
        db_obj = get_active_by_id(session=session, model=model, obj_id=obj_id)
        if db_obj is None:
            raise HTTPException(status_code=404, detail=f"{model_name} not found")
        from app.attendance.services import update_obj

        return public.model_validate(update_obj(session=session, db_obj=db_obj, data=obj_in))

    if not custom_delete:
        @router.delete(
            "/{obj_id}",
            response_model=Message,
            dependencies=[Depends(require_permission(module, "delete"))],
        )
        def delete_route(session: SessionDep, obj_id) -> Any:
            db_obj = get_active_by_id(session=session, model=model, obj_id=obj_id)
            if db_obj is None:
                raise HTTPException(status_code=404, detail=f"{model_name} not found")
            soft_delete_obj(session=session, db_obj=db_obj)
            return Message(message=f"{model_name} deleted successfully")

    return router


# --- Shift ---------------------------------------------------------------------------
shifts_router = _make_crud_router(
    prefix="/shifts",
    tag="shifts",
    module="shifts",
    model=Shift,
    create=s.ShiftCreate,
    update=s.ShiftUpdate,
    public=s.ShiftPublic,
    listing=s.ShiftList,
)


# --- DailyTimeRecord -----------------------------------------------------------------
dtr_router = APIRouter(prefix="/daily-time-records", tags=["daily_time_records"])


@dtr_router.get(
    "/",
    response_model=s.DailyTimeRecordList,
    dependencies=[Depends(require_permission("daily_time_record", "view"))],
)
def list_dtr(session: SessionDep, skip: int = 0, limit: int = 100) -> Any:
    rows, count = get_list(session=session, model=DailyTimeRecord, skip=skip, limit=limit)
    return s.DailyTimeRecordList(
        data=[s.DailyTimeRecordPublic.model_validate(r) for r in rows], count=count
    )


@dtr_router.get(
    "/{obj_id}",
    response_model=s.DailyTimeRecordPublic,
    dependencies=[Depends(require_permission("daily_time_record", "view"))],
)
def read_dtr(session: SessionDep, obj_id) -> Any:
    db_obj = get_active_by_id(session=session, model=DailyTimeRecord, obj_id=obj_id)
    if db_obj is None:
        raise HTTPException(status_code=404, detail="DailyTimeRecord not found")
    return s.DailyTimeRecordPublic.model_validate(db_obj)


@dtr_router.post(
    "/",
    response_model=s.DailyTimeRecordPublic,
    status_code=201,
    dependencies=[Depends(require_permission("daily_time_record", "add"))],
)
def create_dtr_route(
    *, session: SessionDep, obj_in: s.DailyTimeRecordCreate, current_user: CurrentUser
) -> Any:
    db_obj = create_dtr(session=session, data=obj_in, actor_id=current_user.id)
    return s.DailyTimeRecordPublic.model_validate(db_obj)


@dtr_router.patch(
    "/{obj_id}",
    response_model=s.DailyTimeRecordPublic,
    dependencies=[Depends(require_permission("daily_time_record", "edit"))],
)
def update_dtr_route(
    *, session: SessionDep, obj_id, obj_in: s.DailyTimeRecordUpdate, current_user: CurrentUser
) -> Any:
    db_obj = get_active_by_id(session=session, model=DailyTimeRecord, obj_id=obj_id)
    if db_obj is None:
        raise HTTPException(status_code=404, detail="DailyTimeRecord not found")

    shift = None
    if obj_in.shift_id is not None:
        shift = get_active_by_id(session=session, model=Shift, obj_id=obj_in.shift_id)
        if shift is None:
            raise HTTPException(status_code=404, detail="Shift not found")
    elif obj_in.shift_id is None and db_obj.shift_id is not None:
        shift = get_active_by_id(session=session, model=Shift, obj_id=db_obj.shift_id)

    db_obj = update_dtr(
        session=session, db_obj=db_obj, data=obj_in, shift=shift, actor_id=current_user.id
    )
    return s.DailyTimeRecordPublic.model_validate(db_obj)


@dtr_router.delete(
    "/{obj_id}",
    response_model=Message,
    dependencies=[Depends(require_permission("daily_time_record", "delete"))],
)
def delete_dtr(session: SessionDep, obj_id) -> Any:
    db_obj = get_active_by_id(session=session, model=DailyTimeRecord, obj_id=obj_id)
    if db_obj is None:
        raise HTTPException(status_code=404, detail="DailyTimeRecord not found")
    soft_delete_obj(session=session, db_obj=db_obj)
    return Message(message="DailyTimeRecord deleted successfully")


@dtr_router.post(
    "/{obj_id}/approve-overtime",
    response_model=Message,
    dependencies=[Depends(require_permission("daily_time_record", "edit"))],
)
def approve_overtime(
    *, session: SessionDep, obj_id, current_user: CurrentUser
) -> Any:
    """Phase 2B: approve a DTR's overtime (paid only when overtime_approved=True)."""
    db_obj = get_active_by_id(session=session, model=DailyTimeRecord, obj_id=obj_id)
    if db_obj is None:
        raise HTTPException(status_code=404, detail="DailyTimeRecord not found")
    set_overtime_approved(
        session=session, db_obj=db_obj, approved=True, actor_id=current_user.id
    )
    return Message(message="Overtime approved")


@dtr_router.post(
    "/{obj_id}/reject-overtime",
    response_model=Message,
    dependencies=[Depends(require_permission("daily_time_record", "edit"))],
)
def reject_overtime(
    *, session: SessionDep, obj_id, current_user: CurrentUser
) -> Any:
    """Phase 2B: reject a DTR's overtime."""
    db_obj = get_active_by_id(session=session, model=DailyTimeRecord, obj_id=obj_id)
    if db_obj is None:
        raise HTTPException(status_code=404, detail="DailyTimeRecord not found")
    set_overtime_approved(
        session=session, db_obj=db_obj, approved=False, actor_id=current_user.id
    )
    return Message(message="Overtime rejected")


# --- DtrAdjustment (approval flow) -------------------------------------------------
adj_router = APIRouter(prefix="/dtr-adjustments", tags=["dtr_adjustments"])


@adj_router.get(
    "/",
    response_model=adj_s.DtrAdjustmentList,
    dependencies=[Depends(require_permission("daily_time_record", "view"))],
)
def list_adjustments(session: SessionDep, skip: int = 0, limit: int = 100) -> Any:
    rows, count = get_list(session=session, model=DtrAdjustment, skip=skip, limit=limit)
    return adj_s.DtrAdjustmentList(
        data=[adj_s.DtrAdjustmentPublic.model_validate(r) for r in rows], count=count
    )


@adj_router.get(
    "/{obj_id}",
    response_model=adj_s.DtrAdjustmentPublic,
    dependencies=[Depends(require_permission("daily_time_record", "view"))],
)
def read_adjustment(session: SessionDep, obj_id) -> Any:
    db_obj = get_adjustment(session=session, adjustment_id=obj_id)
    if db_obj is None:
        raise HTTPException(status_code=404, detail="DtrAdjustment not found")
    return adj_s.DtrAdjustmentPublic.model_validate(db_obj)


@adj_router.post(
    "/",
    response_model=adj_s.DtrAdjustmentPublic,
    status_code=201,
    dependencies=[Depends(require_permission("daily_time_record", "add"))],
)
def create_adjustment_route(
    *, session: SessionDep, obj_in: adj_s.DtrAdjustmentCreate, current_user: CurrentUser
) -> Any:
    dtr = get_active_by_id(session=session, model=DailyTimeRecord, obj_id=obj_in.daily_time_record_id)
    if dtr is None:
        raise HTTPException(status_code=404, detail="DailyTimeRecord not found")
    db_obj = create_adjustment(
        session=session, data=obj_in, dtr=dtr, actor_id=current_user.id
    )
    return adj_s.DtrAdjustmentPublic.model_validate(db_obj)


@adj_router.post(
    "/{obj_id}/approve",
    response_model=adj_s.DtrAdjustmentPublic,
    dependencies=[Depends(require_permission("daily_time_record", "edit"))],
)
def approve_adjustment_route(
    *, session: SessionDep, obj_id, current_user: CurrentUser
) -> Any:
    db_obj = get_adjustment(session=session, adjustment_id=obj_id)
    if db_obj is None:
        raise HTTPException(status_code=404, detail="DtrAdjustment not found")
    db_obj = approve_adjustment(session=session, adjustment=db_obj, actor_id=current_user.id)
    return adj_s.DtrAdjustmentPublic.model_validate(db_obj)


@adj_router.post(
    "/{obj_id}/reject",
    response_model=adj_s.DtrAdjustmentPublic,
    dependencies=[Depends(require_permission("daily_time_record", "edit"))],
)
def reject_adjustment_route(
    *, session: SessionDep, obj_id, current_user: CurrentUser
) -> Any:
    db_obj = get_adjustment(session=session, adjustment_id=obj_id)
    if db_obj is None:
        raise HTTPException(status_code=404, detail="DtrAdjustment not found")
    db_obj = reject_adjustment(session=session, adjustment=db_obj, actor_id=current_user.id)
    return adj_s.DtrAdjustmentPublic.model_validate(db_obj)


routers: list[APIRouter] = [shifts_router, dtr_router, adj_router]
