import { test, expect } from '../fixtures'
import { apiUrl, waitForWrite, assertWrite } from '../helpers/crud-journey'

test('custom role can be created, renamed and assigned a permission', async ({ page, loginAsAdmin }) => {
  await loginAsAdmin()
  await page.goto('/roles')
  await page.getByTestId('add-role-button').click()
  const unique = Date.now().toString(36)
  await page.getByTestId('role-code-input').fill('R' + unique)
  await page.getByTestId('role-name-input').fill('Role ' + unique)
  const creating = waitForWrite(page, 'rbac/roles', 'POST')
  await page.getByTestId('role-submit-button').click()
  const created = await assertWrite(await creating, 201)
  await expect(page.getByTestId('role-submit-button')).not.toBeVisible()
  await page.getByTestId('edit-role-button-' + created.id).click()
  await expect(page.getByTestId('role-code-input')).toBeDisabled()
  await page.getByTestId('role-name-input').fill('Updated ' + unique)
  const updating = waitForWrite(page, 'rbac/roles', 'PATCH', created.id)
  await page.getByTestId('role-submit-button').click()
  expect((await assertWrite(await updating, 200)).name).toBe('Updated ' + unique)
  await page.getByTestId('role-permission-matrix-button-' + created.id).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.locator('[id="division.view"]').check()
  const saving = waitForWrite(page, 'rbac/roles', 'PATCH', created.id)
  await page.getByRole('button', { name: 'Save Permissions', exact: true }).click()
  await assertWrite(await saving, 200)
  await expect(page.getByRole('dialog')).not.toBeVisible()
  const token = (await page.context().cookies()).find(c => c.name === 'hris_at')!.value
  const response = await page.request.get(apiUrl + '/rbac/roles/' + created.id + '/permissions', { headers: { Authorization: 'Bearer ' + token } })
  expect(response.status()).toBe(200)
  expect((await response.json()).permissions).toContain('division.view')
})
