"""add shift and daily_time_record tables (Phase 2A)

Revision ID: 1c721a424eb4
Revises: b1fd80d00cf0
Create Date: 2026-08-25 12:18:34.132881

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1c721a424eb4'
down_revision = 'b1fd80d00cf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('start_time', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('end_time', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('lunch_break_duration', sa.Integer(), nullable=False),
    sa.Column('total_hours_minus_lunch', sa.Integer(), nullable=False),
    sa.Column('days_of_week', sa.JSON(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_code'), 'shift', ['code'], unique=True)
    op.create_table('daily_time_record',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('shift_id', sa.Uuid(), nullable=True),
    sa.Column('login_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('logout_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rendered_minutes', sa.Integer(), nullable=True),
    sa.Column('late_minutes', sa.Integer(), nullable=True),
    sa.Column('undertime_minutes', sa.Integer(), nullable=True),
    sa.Column('overtime_minutes', sa.Integer(), nullable=True),
    sa.Column('overtime_approved', sa.Boolean(), nullable=True),
    sa.Column('is_absent', sa.Boolean(), nullable=False),
    sa.Column('is_time_calculated', sa.Boolean(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('source_ref', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_time_record_created_by'), 'daily_time_record', ['created_by'], unique=False)
    op.create_index('ix_daily_time_record_employee_deleted', 'daily_time_record', ['employee_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_daily_time_record_employee_id'), 'daily_time_record', ['employee_id'], unique=False)
    op.create_index('ix_daily_time_record_employee_login', 'daily_time_record', ['employee_id', 'login_date'], unique=False)
    op.create_index('ix_daily_time_record_shift_deleted', 'daily_time_record', ['shift_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_daily_time_record_shift_id'), 'daily_time_record', ['shift_id'], unique=False)
    op.create_index(op.f('ix_daily_time_record_updated_by'), 'daily_time_record', ['updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_time_record_updated_by'), table_name='daily_time_record')
    op.drop_index(op.f('ix_daily_time_record_shift_id'), table_name='daily_time_record')
    op.drop_index('ix_daily_time_record_shift_deleted', table_name='daily_time_record')
    op.drop_index('ix_daily_time_record_employee_login', table_name='daily_time_record')
    op.drop_index(op.f('ix_daily_time_record_employee_id'), table_name='daily_time_record')
    op.drop_index('ix_daily_time_record_employee_deleted', table_name='daily_time_record')
    op.drop_index(op.f('ix_daily_time_record_created_by'), table_name='daily_time_record')
    op.drop_table('daily_time_record')
    op.drop_index(op.f('ix_shift_code'), table_name='shift')
    op.drop_table('shift')
    # ### end Alembic commands ###
