"""add notification and audit_log tables

Revision ID: 3009113137ba
Revises: f176e167c8e7
Create Date: 2026-09-15 11:31:48.653985

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3009113137ba'
down_revision = 'f176e167c8e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
