"""add_payroll_tables

Revision ID: 54ff6e36652b
Revises: a1b2c3d4e5f6
Create Date: 2026-09-19 00:48:59.969445

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '54ff6e36652b'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_salary', 'de_minimis_monthly',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_index(op.f('ix_employee_salary_employee_id'), table_name='employee_salary')
    op.drop_constraint(op.f('uq_employee_salary_employee_date'), 'employee_salary', type_='unique')
    op.create_unique_constraint('uq_employee_salary_employee_id', 'employee_salary', ['employee_id'])
    op.alter_column('integration_config', 'headers',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.create_index(op.f('ix_integration_config_name'), 'integration_config', ['name'], unique=False)
    op.drop_index(op.f('ix_integration_mapping_integration_config_id'), table_name='integration_mapping')
    op.drop_index(op.f('ix_loan_employee_id'), table_name='loan')
    op.drop_index(op.f('ix_loan_amortization_loan_id'), table_name='loan_amortization')
    op.alter_column('payroll_entry', 'earnings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('payroll_entry', 'deductions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_index(op.f('ix_payroll_entry_employee_id'), table_name='payroll_entry')
    op.drop_index(op.f('ix_payroll_entry_payroll_run_id'), table_name='payroll_entry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_payroll_entry_payroll_run_id'), 'payroll_entry', ['payroll_run_id'], unique=False)
    op.create_index(op.f('ix_payroll_entry_employee_id'), 'payroll_entry', ['employee_id'], unique=False)
    op.alter_column('payroll_entry', 'deductions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('payroll_entry', 'earnings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.create_index(op.f('ix_loan_amortization_loan_id'), 'loan_amortization', ['loan_id'], unique=False)
    op.create_index(op.f('ix_loan_employee_id'), 'loan', ['employee_id'], unique=False)
    op.create_index(op.f('ix_integration_mapping_integration_config_id'), 'integration_mapping', ['integration_config_id'], unique=False)
    op.drop_index(op.f('ix_integration_config_name'), table_name='integration_config')
    op.alter_column('integration_config', 'headers',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_constraint('uq_employee_salary_employee_id', 'employee_salary', type_='unique')
    op.create_unique_constraint(op.f('uq_employee_salary_employee_date'), 'employee_salary', ['employee_id', 'effective_date'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_employee_salary_employee_id'), 'employee_salary', ['employee_id'], unique=False)
    op.alter_column('employee_salary', 'de_minimis_monthly',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###
