"""Add monthly payroll contribution ledger

Revision ID: 67e279f8c3cc
Revises: 9d04b5c6d7e8
Create Date: 2026-10-07 16:55:42.805818

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '67e279f8c3cc'
down_revision = '9d04b5c6d7e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_contribution_ledger',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('payroll_entry_id', sa.Uuid(), nullable=False),
    sa.Column('scheme', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('contribution_month', sa.Date(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('monthly_basis', sa.Numeric(12, 2), nullable=False),
    sa.Column('employee_amount', sa.Numeric(12, 2), nullable=False),
    sa.Column('employer_amount', sa.Numeric(12, 2), nullable=False),
    sa.Column('calculation_snapshot', sa.JSON(), nullable=False),
    sa.Column('source_references', sa.JSON(), nullable=False),
    sa.Column('adjustment_reason', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('reverses_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("scheme IN ('sss', 'philhealth', 'pagibig')", name='ck_payroll_contribution_scheme'),
    sa.CheckConstraint('(sequence = 0 AND adjustment_reason IS NULL AND reverses_id IS NULL) OR (sequence > 0 AND adjustment_reason IS NOT NULL AND reverses_id IS NOT NULL)', name='ck_payroll_contribution_adjustment_reason'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_records.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payroll_entry_id'], ['payroll_entry.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reverses_id'], ['payroll_contribution_ledger.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'scheme', 'contribution_month', 'sequence', name='uq_payroll_contribution_employee_scheme_month_sequence'),
    sa.UniqueConstraint('payroll_entry_id', 'scheme', 'sequence', name='uq_payroll_contribution_entry_scheme_sequence')
    )
    op.create_index('ix_payroll_contribution_employee_month', 'payroll_contribution_ledger', ['employee_id', 'contribution_month'], unique=False)
    op.create_index(op.f('ix_payroll_contribution_ledger_employee_id'), 'payroll_contribution_ledger', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_contribution_ledger_payroll_entry_id'), 'payroll_contribution_ledger', ['payroll_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payroll_contribution_ledger_payroll_entry_id'), table_name='payroll_contribution_ledger')
    op.drop_index(op.f('ix_payroll_contribution_ledger_employee_id'), table_name='payroll_contribution_ledger')
    op.drop_index('ix_payroll_contribution_employee_month', table_name='payroll_contribution_ledger')
    op.drop_table('payroll_contribution_ledger')
    # ### end Alembic commands ###
