"""add employee core and org structure tables

Revision ID: 7286295e0903
Revises: 10fc690ffb09
Create Date: 2026-08-10 14:08:13.247487

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7286295e0903'
down_revision = '10fc690ffb09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: foreign keys are created at the end (op.create_foreign_key) because
    # several tables reference each other in a cycle (division/department/position
    # <-> employee_records, category <-> lots), which PostgreSQL cannot resolve
    # if the constraint is emitted inside create_table. Every referenced table
    # must exist before any FK is added.
    op.create_table('category',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_overhead', sa.Boolean(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=True),
    sa.Column('phase_id', sa.Uuid(), nullable=False),
    sa.Column('blocks_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('lot_id', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_blocks_id'), 'category', ['blocks_id'], unique=False)
    op.create_index(op.f('ix_category_code'), 'category', ['code'], unique=True)
    op.create_index(op.f('ix_category_lot_id'), 'category', ['lot_id'], unique=False)
    op.create_index(op.f('ix_category_model_id'), 'category', ['model_id'], unique=False)
    op.create_index(op.f('ix_category_owner_id'), 'category', ['owner_id'], unique=False)
    op.create_index('ix_category_phase_deleted', 'category', ['phase_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_category_phase_id'), 'category', ['phase_id'], unique=False)
    op.create_index('ix_category_project_deleted', 'category', ['project_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_category_project_id'), 'category', ['project_id'], unique=False)
    op.create_table('department',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('division_id', sa.Uuid(), nullable=False),
    sa.Column('manager_id', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_code'), 'department', ['code'], unique=True)
    op.create_index('ix_department_division_deleted', 'department', ['division_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_department_division_id'), 'department', ['division_id'], unique=False)
    op.create_index(op.f('ix_department_manager_id'), 'department', ['manager_id'], unique=False)
    op.create_table('division',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('director_id', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_division_code'), 'division', ['code'], unique=True)
    op.create_index(op.f('ix_division_director_id'), 'division', ['director_id'], unique=False)
    op.create_table('employee_records',
    sa.Column('employee_code', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('middle_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('extension', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('birth_place', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('civil_status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('zip_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('area', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('present_barangay', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('present_city', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('same_address', sa.Boolean(), nullable=True),
    sa.Column('permanent_barangay', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('permanent_city', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('date_hired', sa.Date(), nullable=True),
    sa.Column('employee_status', sa.Enum('ACTIVE', 'RESIGNED', 'TERMINATED', 'ON_LEAVE', name='employeestatus'), nullable=False),
    sa.Column('employment_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('contract_expiry_date', sa.Date(), nullable=True),
    sa.Column('date_separated', sa.Date(), nullable=True),
    sa.Column('probationary_date', sa.Date(), nullable=True),
    sa.Column('regularization_date', sa.Date(), nullable=True),
    sa.Column('telephone', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('cellphone', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('profile_photo_path', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('division_id', sa.Uuid(), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('position_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_code', name='uq_employee_records_employee_code')
    )
    op.create_index('ix_employee_records_department_deleted', 'employee_records', ['department_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_employee_records_department_id'), 'employee_records', ['department_id'], unique=False)
    op.create_index('ix_employee_records_division_deleted', 'employee_records', ['division_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_employee_records_division_id'), 'employee_records', ['division_id'], unique=False)
    op.create_index(op.f('ix_employee_records_position_id'), 'employee_records', ['position_id'], unique=False)
    op.create_index('ix_employee_records_status_deleted', 'employee_records', ['employee_status', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_employee_records_user_id'), 'employee_records', ['user_id'], unique=False)
    op.create_table('lots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lot_num', sa.Integer(), nullable=True),
    sa.Column('lot_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('blocks_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', name='uq_lots_category_id')
    )
    op.create_index('ix_lots_blocks_deleted', 'lots', ['blocks_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_lots_blocks_id'), 'lots', ['blocks_id'], unique=False)
    op.create_index(op.f('ix_lots_category_id'), 'lots', ['category_id'], unique=False)
    op.create_table('model_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('additional_options', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_types_code'), 'model_types', ['code'], unique=True)
    op.create_table('owner',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('lot_no', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('block', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('contact_no', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_code'), 'position', ['code'], unique=True)
    op.create_index(op.f('ix_position_department_id'), 'position', ['department_id'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('subdivision_id', sa.Uuid(), nullable=False),
    sa.Column('project_type_id', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_code'), 'project', ['code'], unique=True)
    op.create_index('ix_project_project_type_deleted', 'project', ['project_type_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_project_project_type_id'), 'project', ['project_type_id'], unique=False)
    op.create_index('ix_project_subdivision_deleted', 'project', ['subdivision_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_project_subdivision_id'), 'project', ['subdivision_id'], unique=False)
    op.create_table('project_type',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_type_code'), 'project_type', ['code'], unique=True)
    op.create_table('subdivision',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subdivision_code', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subdivision_subdivision_code'), 'subdivision', ['subdivision_code'], unique=True)
    op.create_table('employee_additional_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('employment_history', sa.JSON(), nullable=True),
    sa.Column('past_employment_record', sa.JSON(), nullable=True),
    sa.Column('educational_background', sa.JSON(), nullable=True),
    sa.Column('seminars_trainings', sa.JSON(), nullable=True),
    sa.Column('assessments_exams', sa.JSON(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('awards', sa.JSON(), nullable=True),
    sa.Column('licenses', sa.JSON(), nullable=True),
    sa.Column('dependents', sa.JSON(), nullable=True),
    sa.Column('violations', sa.JSON(), nullable=True),
    sa.Column('medical_drug_tests', sa.JSON(), nullable=True),
    sa.Column('school_graduated', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('course', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('career_band_level', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('career_global_grade', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('cash_card_number', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('hmo_account', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('sss_number', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('philhealth_number', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('pagibig_number', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('tin_number', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', name='uq_employee_additional_records_employee_id')
    )
    op.create_index(op.f('ix_employee_additional_records_employee_id'), 'employee_additional_records', ['employee_id'], unique=False)
    op.create_table('employee_attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('attachment_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('attachment_size', sa.Integer(), nullable=True),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('original_file_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('date_uploaded', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_attachments_employee_id'), 'employee_attachments', ['employee_id'], unique=False)
    op.create_table('employee_projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rendered_hours', sa.Integer(), nullable=True),
    sa.Column('task', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('is_assigned', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'project_id', name='uq_employee_projects_employee_project')
    )
    op.create_index('ix_employee_projects_employee_deleted', 'employee_projects', ['employee_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_employee_projects_employee_id'), 'employee_projects', ['employee_id'], unique=False)
    op.create_index('ix_employee_projects_project_deleted', 'employee_projects', ['project_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_employee_projects_project_id'), 'employee_projects', ['project_id'], unique=False)
    op.create_table('model',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('model_type_id', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_model_type_id'), 'model', ['model_type_id'], unique=False)
    op.create_table('phase',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('subdivision_id', sa.Uuid(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phase_code'), 'phase', ['code'], unique=True)
    op.create_index('ix_phase_subdivision_deleted', 'phase', ['subdivision_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_phase_subdivision_id'), 'phase', ['subdivision_id'], unique=False)
    op.create_table('blocks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('block_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('phase_id', sa.Uuid(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_blocks_phase_deleted', 'blocks', ['phase_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_blocks_phase_id'), 'blocks', ['phase_id'], unique=False)
    op.create_table('emp_task',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('emp_project_id', sa.Uuid(), nullable=False),
    sa.Column('task_desc', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('rendered_hours', sa.Integer(), nullable=True),
    sa.Column('assigned_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('is_adjusted', sa.Boolean(), nullable=True),
    sa.Column('worker_logs_id', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_emp_task_emp_project_deleted', 'emp_task', ['emp_project_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_emp_task_emp_project_id'), 'emp_task', ['emp_project_id'], unique=False)
    op.create_index(op.f('ix_emp_task_worker_logs_id'), 'emp_task', ['worker_logs_id'], unique=False)
    # ### end Alembic commands ###

    # --- Foreign keys added after all tables exist (circular refs) ----------
    op.create_foreign_key('fk_division_director', 'division', 'employee_records', ['director_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_department_division', 'department', 'division', ['division_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_department_manager', 'department', 'employee_records', ['manager_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_employee_records_division', 'employee_records', 'division', ['division_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_employee_records_department', 'employee_records', 'department', ['department_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_employee_records_position', 'employee_records', 'position', ['position_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_employee_records_user', 'employee_records', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_position_department', 'position', 'department', ['department_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_project_subdivision', 'project', 'subdivision', ['subdivision_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_project_project_type', 'project', 'project_type', ['project_type_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_phase_subdivision', 'phase', 'subdivision', ['subdivision_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_blocks_phase', 'blocks', 'phase', ['phase_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_lots_blocks', 'lots', 'blocks', ['blocks_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_lots_category', 'lots', 'category', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_category_project', 'category', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_category_model', 'category', 'model', ['model_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_category_phase', 'category', 'phase', ['phase_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_category_blocks', 'category', 'blocks', ['blocks_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_category_owner', 'category', 'owner', ['owner_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_category_lots', 'category', 'lots', ['lot_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_model_model_types', 'model', 'model_types', ['model_type_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_employee_additional_records_employee', 'employee_additional_records', 'employee_records', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_employee_attachments_employee', 'employee_attachments', 'employee_records', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_employee_projects_employee', 'employee_projects', 'employee_records', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_employee_projects_project', 'employee_projects', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_emp_task_employee_projects', 'emp_task', 'employee_projects', ['emp_project_id'], ['id'], ondelete='CASCADE')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_emp_task_employee_projects', 'emp_task', type_='foreignkey')
    op.drop_constraint('fk_employee_projects_project', 'employee_projects', type_='foreignkey')
    op.drop_constraint('fk_employee_projects_employee', 'employee_projects', type_='foreignkey')
    op.drop_constraint('fk_employee_attachments_employee', 'employee_attachments', type_='foreignkey')
    op.drop_constraint('fk_employee_additional_records_employee', 'employee_additional_records', type_='foreignkey')
    op.drop_constraint('fk_model_model_types', 'model', type_='foreignkey')
    op.drop_constraint('fk_category_lots', 'category', type_='foreignkey')
    op.drop_constraint('fk_category_owner', 'category', type_='foreignkey')
    op.drop_constraint('fk_category_blocks', 'category', type_='foreignkey')
    op.drop_constraint('fk_category_phase', 'category', type_='foreignkey')
    op.drop_constraint('fk_category_model', 'category', type_='foreignkey')
    op.drop_constraint('fk_category_project', 'category', type_='foreignkey')
    op.drop_constraint('fk_lots_category', 'lots', type_='foreignkey')
    op.drop_constraint('fk_lots_blocks', 'lots', type_='foreignkey')
    op.drop_constraint('fk_blocks_phase', 'blocks', type_='foreignkey')
    op.drop_constraint('fk_phase_subdivision', 'phase', type_='foreignkey')
    op.drop_constraint('fk_project_project_type', 'project', type_='foreignkey')
    op.drop_constraint('fk_project_subdivision', 'project', type_='foreignkey')
    op.drop_constraint('fk_position_department', 'position', type_='foreignkey')
    op.drop_constraint('fk_employee_records_user', 'employee_records', type_='foreignkey')
    op.drop_constraint('fk_employee_records_position', 'employee_records', type_='foreignkey')
    op.drop_constraint('fk_employee_records_department', 'employee_records', type_='foreignkey')
    op.drop_constraint('fk_employee_records_division', 'employee_records', type_='foreignkey')
    op.drop_constraint('fk_department_manager', 'department', type_='foreignkey')
    op.drop_constraint('fk_department_division', 'department', type_='foreignkey')
    op.drop_constraint('fk_division_director', 'division', type_='foreignkey')
    op.drop_index(op.f('ix_emp_task_worker_logs_id'), table_name='emp_task')
    op.drop_index(op.f('ix_emp_task_emp_project_id'), table_name='emp_task')
    op.drop_index('ix_emp_task_emp_project_deleted', table_name='emp_task')
    op.drop_table('emp_task')
    op.drop_index(op.f('ix_blocks_phase_id'), table_name='blocks')
    op.drop_index('ix_blocks_phase_deleted', table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_phase_subdivision_id'), table_name='phase')
    op.drop_index('ix_phase_subdivision_deleted', table_name='phase')
    op.drop_index(op.f('ix_phase_code'), table_name='phase')
    op.drop_table('phase')
    op.drop_index(op.f('ix_model_model_type_id'), table_name='model')
    op.drop_table('model')
    op.drop_index(op.f('ix_employee_projects_project_id'), table_name='employee_projects')
    op.drop_index('ix_employee_projects_project_deleted', table_name='employee_projects')
    op.drop_index(op.f('ix_employee_projects_employee_id'), table_name='employee_projects')
    op.drop_index('ix_employee_projects_employee_deleted', table_name='employee_projects')
    op.drop_table('employee_projects')
    op.drop_index(op.f('ix_employee_attachments_employee_id'), table_name='employee_attachments')
    op.drop_table('employee_attachments')
    op.drop_index(op.f('ix_employee_additional_records_employee_id'), table_name='employee_additional_records')
    op.drop_table('employee_additional_records')
    op.drop_index(op.f('ix_subdivision_subdivision_code'), table_name='subdivision')
    op.drop_table('subdivision')
    op.drop_index(op.f('ix_project_type_code'), table_name='project_type')
    op.drop_table('project_type')
    op.drop_index(op.f('ix_project_subdivision_id'), table_name='project')
    op.drop_index('ix_project_subdivision_deleted', table_name='project')
    op.drop_index(op.f('ix_project_project_type_id'), table_name='project')
    op.drop_index('ix_project_project_type_deleted', table_name='project')
    op.drop_index(op.f('ix_project_code'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_position_department_id'), table_name='position')
    op.drop_index(op.f('ix_position_code'), table_name='position')
    op.drop_table('position')
    op.drop_table('owner')
    op.drop_index(op.f('ix_model_types_code'), table_name='model_types')
    op.drop_table('model_types')
    op.drop_index(op.f('ix_lots_category_id'), table_name='lots')
    op.drop_index(op.f('ix_lots_blocks_id'), table_name='lots')
    op.drop_index('ix_lots_blocks_deleted', table_name='lots')
    op.drop_table('lots')
    op.drop_index(op.f('ix_employee_records_user_id'), table_name='employee_records')
    op.drop_index('ix_employee_records_status_deleted', table_name='employee_records')
    op.drop_index(op.f('ix_employee_records_position_id'), table_name='employee_records')
    op.drop_index(op.f('ix_employee_records_division_id'), table_name='employee_records')
    op.drop_index('ix_employee_records_division_deleted', table_name='employee_records')
    op.drop_index(op.f('ix_employee_records_department_id'), table_name='employee_records')
    op.drop_index('ix_employee_records_department_deleted', table_name='employee_records')
    op.drop_table('employee_records')
    op.drop_index(op.f('ix_division_director_id'), table_name='division')
    op.drop_index(op.f('ix_division_code'), table_name='division')
    op.drop_table('division')
    op.drop_index(op.f('ix_department_manager_id'), table_name='department')
    op.drop_index(op.f('ix_department_division_id'), table_name='department')
    op.drop_index('ix_department_division_deleted', table_name='department')
    op.drop_index(op.f('ix_department_code'), table_name='department')
    op.drop_table('department')
    op.drop_index(op.f('ix_category_project_id'), table_name='category')
    op.drop_index('ix_category_project_deleted', table_name='category')
    op.drop_index(op.f('ix_category_phase_id'), table_name='category')
    op.drop_index('ix_category_phase_deleted', table_name='category')
    op.drop_index(op.f('ix_category_owner_id'), table_name='category')
    op.drop_index(op.f('ix_category_model_id'), table_name='category')
    op.drop_index(op.f('ix_category_lot_id'), table_name='category')
    op.drop_index(op.f('ix_category_code'), table_name='category')
    op.drop_index(op.f('ix_category_blocks_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
