"""add is_deleted to audit_log

Revision ID: 9c7a54c3b67f
Revises: bc349a74ea22
Create Date: 2026-09-15 11:54:02.381651

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9c7a54c3b67f'
down_revision = 'bc349a74ea22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_log', 'is_deleted')
    # ### end Alembic commands ###
