"""add unique index on category lot_id

Revision ID: b1fd80d00cf0
Revises: 7286295e0903
Create Date: 2026-08-10 14:14:43.897371

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b1fd80d00cf0'
down_revision = '7286295e0903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_lot_id'), table_name='category')
    op.create_index(op.f('ix_category_lot_id'), 'category', ['lot_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_lot_id'), table_name='category')
    op.create_index(op.f('ix_category_lot_id'), 'category', ['lot_id'], unique=False)
    # ### end Alembic commands ###
