"""add dtr_adjustment table (Phase 2B)

Revision ID: c3b726b97e47
Revises: 1c721a424eb4
Create Date: 2026-08-25 13:03:19.350111

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c3b726b97e47'
down_revision = '1c721a424eb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dtr_adjustment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('daily_time_record_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('original_login_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('original_logout_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('adjusted_login_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('adjusted_logout_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('adjusted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['daily_time_record_id'], ['daily_time_record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dtr_adjustment_approved_by'), 'dtr_adjustment', ['approved_by'], unique=False)
    op.create_index(op.f('ix_dtr_adjustment_created_by'), 'dtr_adjustment', ['created_by'], unique=False)
    op.create_index(op.f('ix_dtr_adjustment_daily_time_record_id'), 'dtr_adjustment', ['daily_time_record_id'], unique=False)
    op.create_index('ix_dtr_adjustment_dtr_deleted', 'dtr_adjustment', ['daily_time_record_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_dtr_adjustment_employee_id'), 'dtr_adjustment', ['employee_id'], unique=False)
    op.create_index(op.f('ix_dtr_adjustment_status'), 'dtr_adjustment', ['status'], unique=False)
    op.create_index('ix_dtr_adjustment_status_deleted', 'dtr_adjustment', ['status', 'is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dtr_adjustment_status_deleted', table_name='dtr_adjustment')
    op.drop_index(op.f('ix_dtr_adjustment_status'), table_name='dtr_adjustment')
    op.drop_index(op.f('ix_dtr_adjustment_employee_id'), table_name='dtr_adjustment')
    op.drop_index('ix_dtr_adjustment_dtr_deleted', table_name='dtr_adjustment')
    op.drop_index(op.f('ix_dtr_adjustment_daily_time_record_id'), table_name='dtr_adjustment')
    op.drop_index(op.f('ix_dtr_adjustment_created_by'), table_name='dtr_adjustment')
    op.drop_index(op.f('ix_dtr_adjustment_approved_by'), table_name='dtr_adjustment')
    op.drop_table('dtr_adjustment')
    # ### end Alembic commands ###
