"""change employee_salary unique constraint to include effective_date

Revision ID: f176e167c8e7
Revises: d5b5b4e1b4a2
Create Date: 2026-09-14 18:57:45.605711

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f176e167c8e7'
down_revision = 'd5b5b4e1b4a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_employee_salary_employee_id'), 'employee_salary', type_='unique')
    op.create_unique_constraint('uq_employee_salary_employee_date', 'employee_salary', ['employee_id', 'effective_date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_employee_salary_employee_date', 'employee_salary', type_='unique')
    op.create_unique_constraint(op.f('uq_employee_salary_employee_id'), 'employee_salary', ['employee_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
