"""Central SQLModel table registry.

Every table model in the application must be imported here. Alembic's
autogenerate compares ``SQLModel.metadata`` against the live database, so a
model that is not reachable from this module is invisible to migrations and
will be silently omitted (or, worse, autogenerated as a DROP).

Import this module for its side effects only.
"""

from sqlmodel import SQLModel

from app.auth.models import RefreshToken
from app.attendance.adjustment_models import DtrAdjustment
from app.attendance.models import DailyTimeRecord, Shift
from app.employee.models import (
    Blocks,
    Category,
    Department,
    Division,
    EmployeeAdditionalRecords,
    EmployeeAttachments,
    EmployeeProjects,
    EmployeeRecords,
    EmpTask,
    Lots,
    Model,
    ModelTypes,
    Owner,
    Phase,
    Position,
    Project,
    ProjectType,
    Subdivision,
)
from app.item.models import Item
from app.rbac.models import Module, Role, RolePermission
from app.user.models import User

__all__ = [
    "SQLModel",
    "Item",
    "Module",
    "RefreshToken",
    "Role",
    "RolePermission",
    "User",
    "Blocks",
    "Category",
    "Department",
    "Division",
    "EmpTask",
    "EmployeeAdditionalRecords",
    "EmployeeAttachments",
    "EmployeeProjects",
    "EmployeeRecords",
    "Lots",
    "Model",
    "ModelTypes",
    "Owner",
    "Phase",
    "Position",
    "Project",
    "ProjectType",
    "Subdivision",
    "Shift",
    "DailyTimeRecord",
    "DtrAdjustment",
]
