"""Central SQLModel table registry.

Every table model in the application must be imported here. Alembic's
autogenerate compares ``SQLModel.metadata`` against the live database, so a
model that is not reachable from this module is invisible to migrations and
will be silently omitted (or, worse, autogenerated as a DROP).

Import this module for its side effects only.
"""

from sqlmodel import SQLModel

from app.attendance.adjustment_models import DtrAdjustment
from app.attendance.models import DailyTimeRecord, Shift
from app.audit.models import AuditLog
from app.auth.models import RefreshToken
from app.employee.models import (
    Blocks,
    Category,
    Department,
    Division,
    EmployeeAdditionalRecords,
    EmployeeAttachments,
    EmployeeProjects,
    EmployeeRecords,
    EmpTask,
    Lots,
    Model,
    ModelTypes,
    Owner,
    Phase,
    Position,
    Project,
    ProjectType,
    Subdivision,
)
from app.item.models import Item
from app.leave.models import (
    EmployeeLeaveEnrollment,
    HolidayConfig,
    HolidayInstance,
    LeaveLedgerEntry,
    LeavePolicy,
    LeaveRequest,
    LeaveRequestEvent,
)
from app.notification.models import Notification
from app.payroll.models import (
    BIRBracket,
    ConnectorType,
    CutoffType,
    EmployeeSalary,
    IntegrationConfig,
    IntegrationMapping,
    Loan,
    LoanAmortization,
    LoanType,
    PagIBIGBracket,
    PayrollAdjustmentType,
    PayrollEntry,
    PayrollRun,
    PayrollRunStatus,
    PayType,
    PhilHealthBracket,
    SSSBracket,
)
from app.rbac.models import Module, Role, RolePermission
from app.user.models import User

__all__ = [
    "SQLModel",
    "Item",
    "Module",
    "RefreshToken",
    "Role",
    "RolePermission",
    "User",
    "AuditLog",
    "BIRBracket",
    "Blocks",
    "Category",
    "ConnectorType",
    "CutoffType",
    "Department",
    "Division",
    "EmpTask",
    "EmployeeAdditionalRecords",
    "EmployeeAttachments",
    "EmployeeLeaveEnrollment",
    "EmployeeProjects",
    "EmployeeRecords",
    "EmployeeSalary",
    "HolidayConfig",
    "HolidayInstance",
    "IntegrationConfig",
    "IntegrationMapping",
    "Lots",
    "LeaveLedgerEntry",
    "LeavePolicy",
    "LeaveRequest",
    "LeaveRequestEvent",
    "Loan",
    "LoanAmortization",
    "LoanType",
    "Model",
    "ModelTypes",
    "Notification",
    "Owner",
    "PagIBIGBracket",
    "PayrollAdjustmentType",
    "PayrollEntry",
    "PayrollRun",
    "PayrollRunStatus",
    "PayType",
    "Phase",
    "PhilHealthBracket",
    "Position",
    "Project",
    "ProjectType",
    "SSSBracket",
    "Subdivision",
    "Shift",
    "DailyTimeRecord",
    "DtrAdjustment",
]
