import { test, expect } from '../fixtures'
import { createParent, crudJourney, selectLabel, waitForWrite, assertWrite } from '../helpers/crud-journey'
import { subdivision } from '../helpers/parent-records'
test('categories preserve their complete parent chain through CRUD', async ({ page, loginAsAdmin }) => {
 await loginAsAdmin()
 const unique = Date.now().toString(36)
 const sub = await subdivision(page, unique)
 const project = await createParent(page, 'projects', { code: 'P' + unique, name: 'Project ' + unique, subdivision_id: sub.id })
 const phase = await createParent(page, 'phases', { code: 'H' + unique, name: 'Phase ' + unique, subdivision_id: sub.id })
 const block = await createParent(page, 'blocks', { block_name: 'Block ' + unique, phase_id: phase.id })
 const lot = await createParent(page, 'lots', { lot_name: 'Lot ' + unique, lot_num: 101, blocks_id: block.id })
 await crudJourney(page, { route: 'categories', prefix: 'category', fields: { code: 'C' + unique, description: 'Original ' + unique }, editField: 'description', editValue: 'Reviewed ' + unique, expected: { project_id: project.id, phase_id: phase.id, blocks_id: block.id, lot_id: lot.id, is_overhead: false }, prepare: async () => {
  await selectLabel(page, 'category-project-select', project.name)
  await selectLabel(page, 'category-phase-select', phase.name)
  await selectLabel(page, 'category-blocks-select', block.block_name)
  await selectLabel(page, 'category-lot-select', lot.lot_name)
 } })
})
test('subdivision wizard writes project before category with real parent selections', async ({ page, loginAsAdmin }) => {
 await loginAsAdmin()
 const unique = Date.now().toString(36)
 const sub = await subdivision(page, unique)
 const phase = await createParent(page, 'phases', { code: 'W' + unique, name: 'Wizard phase ' + unique, subdivision_id: sub.id })
 await page.goto('/subdivisions')
 await page.getByRole('button', { name: /wizard/i }).click()
 await selectLabel(page, 'wizard-subdivision-select', sub.subdivision_code + ' - ' + sub.name)
 await page.getByRole('button', { name: 'Next', exact: true }).click()
 await page.getByTestId('wizard-category-code-input').fill('WC' + unique)
 await page.getByRole('button', { name: 'Next', exact: true }).click()
 await page.getByTestId('wizard-project-code-input').fill('WP' + unique)
 await page.getByTestId('wizard-project-name-input').fill('Wizard project ' + unique)
 await selectLabel(page, 'wizard-phase-select', phase.name)
 const projectWrite = waitForWrite(page, 'projects', 'POST')
 const categoryWrite = waitForWrite(page, 'categories', 'POST')
 await page.getByRole('button', { name: 'Create Project & Category', exact: true }).click()
 const project = await assertWrite(await projectWrite, 201)
 const category = await assertWrite(await categoryWrite, 201)
 expect(category.project_id).toBe(project.id)
 expect(category.phase_id).toBe(phase.id)
 expect(category.code).toBe('WC' + unique)
 await expect(page.getByRole('button', { name: 'Create Project & Category', exact: true })).not.toBeVisible()
})
