"""Phase 1 routers: Employee core + Org structure + Construction/manpower.

Every route is gated by ``require_permission(module, action)`` from Phase 0
(see app/rbac/dependencies.py). CRUD shape is generated by ``_make_crud_router``;
resources with special behaviour (delete-guards, approve/deny, ownership reads)
declare additional handlers on their router.
"""

from typing import Any

from fastapi import APIRouter, Depends, File, Form, HTTPException, UploadFile

from app.common.dependencies import CurrentUser, SessionDep
from app.common.schemas import Message
from app.employee import models as m
from app.employee import schemas as s
from app.employee.selectors import (
    get_active_by_id,
    get_additional_records_for_employee,
    get_attachment_by_id,
    get_attachments_for_employee,
    get_list,
)
from app.employee.services import (
    create_attachment,
    create_obj,
    ensure_not_referenced_by_active_category,
    soft_delete_attachment,
    soft_delete_obj,
    store_attachment_file,
    update_obj,
    upsert_additional_records,
)
from app.rbac.dependencies import require_permission
from app.rbac.models import PermissionAction
from app.rbac.services import user_has_permission

Type = type


def _employee_or_404(session: SessionDep, employee_id) -> m.EmployeeRecords:
    emp = get_active_by_id(session=session, model=m.EmployeeRecords, obj_id=employee_id)
    if emp is None:
        raise HTTPException(status_code=404, detail="Employee not found")
    return emp


def _ensure_annex_access(
    session: SessionDep,
    current_user: CurrentUser,
    employee: m.EmployeeRecords,
    *,
    elevated_action: PermissionAction = PermissionAction.EDIT,
) -> None:
    """Ownership check for 201-file annex/attachments.

    A user may access their OWN record (EmployeeRecords.user_id == caller). A
    non-owner must hold an elevated ``emp_list`` permission for the action.
    """
    if employee.user_id == current_user.id:
        return
    if user_has_permission(
        session=session, user=current_user, module_code="emp_list", action=elevated_action
    ):
        return
    raise HTTPException(
        status_code=403, detail="Not enough permissions to access this employee's records"
    )


def _make_crud_router(
    *,
    prefix: str,
    tag: str,
    module: str,
    model: Type,
    create: Type,
    update: Type,
    public: Type,
    listing: Type,
    custom_delete: bool = False,
) -> APIRouter:
    router = APIRouter(prefix=prefix, tags=[tag])
    model_name = model.__name__

    @router.get(
        "/",
        response_model=listing,
        dependencies=[Depends(require_permission(module, "view"))],
    )
    def list_objs(session: SessionDep, skip: int = 0, limit: int = 100) -> Any:
        rows, count = get_list(session=session, model=model, skip=skip, limit=limit)
        return listing(data=[public.model_validate(r) for r in rows], count=count)

    @router.get(
        "/{obj_id}",
        response_model=public,
        dependencies=[Depends(require_permission(module, "view"))],
    )
    def read_obj(session: SessionDep, obj_id) -> Any:
        db_obj = get_active_by_id(session=session, model=model, obj_id=obj_id)
        if db_obj is None:
            raise HTTPException(status_code=404, detail=f"{model_name} not found")
        return public.model_validate(db_obj)

    @router.post(
        "/",
        response_model=public,
        status_code=201,
        dependencies=[Depends(require_permission(module, "add"))],
    )
    def create_route(*, session: SessionDep, obj_in: create) -> Any:
        db_obj = create_obj(session=session, model=model, data=obj_in)
        return public.model_validate(db_obj)

    @router.patch(
        "/{obj_id}",
        response_model=public,
        dependencies=[Depends(require_permission(module, "edit"))],
    )
    def update_route(*, session: SessionDep, obj_id, obj_in: update) -> Any:
        db_obj = get_active_by_id(session=session, model=model, obj_id=obj_id)
        if db_obj is None:
            raise HTTPException(status_code=404, detail=f"{model_name} not found")
        return public.model_validate(update_obj(session=session, db_obj=db_obj, data=obj_in))

    if not custom_delete:
        @router.delete(
            "/{obj_id}",
            response_model=Message,
            dependencies=[Depends(require_permission(module, "delete"))],
        )
        def delete_route(session: SessionDep, obj_id) -> Any:
            db_obj = get_active_by_id(session=session, model=model, obj_id=obj_id)
            if db_obj is None:
                raise HTTPException(status_code=404, detail=f"{model_name} not found")
            soft_delete_obj(session=session, db_obj=db_obj)
            return Message(message=f"{model_name} deleted successfully")

    return router


# --- Employees ---------------------------------------------------------------
employees_router = _make_crud_router(
    prefix="/employees",
    tag="employees",
    module="emp_list",
    model=m.EmployeeRecords,
    create=s.EmployeeRecordsCreate,
    update=s.EmployeeRecordsUpdate,
    public=s.EmployeeRecordsPublic,
    listing=s.EmployeeRecordsList,
)


@employees_router.get(
    "/me",
    response_model=s.EmployeeRecordsPublic,
    dependencies=[Depends(require_permission("emp_list", "view"))],
)
def read_own_employee(session: SessionDep, current_user: CurrentUser) -> Any:
    """Self-service read of the caller's own employee record (ownership check)."""
    db_obj = get_list(
        session=session, model=m.EmployeeRecords,
        filter_column=m.EmployeeRecords.user_id, filter_value=current_user.id, limit=1,
    )[0]
    if not db_obj:
        raise HTTPException(status_code=404, detail="No employee record for this user")
    return s.EmployeeRecordsPublic.model_validate(db_obj[0])


@employees_router.get(
    "/{employee_id}/additional-records",
    response_model=s.EmployeeAdditionalRecordsPublic,
)
def read_additional_records(
    session: SessionDep, employee_id, current_user: CurrentUser
) -> Any:
    """Read a single employee's 201-file annex (ownership-checked)."""
    employee = _employee_or_404(session, employee_id)
    _ensure_annex_access(session, current_user, employee, elevated_action=PermissionAction.VIEW)
    annex = get_additional_records_for_employee(session=session, employee_id=employee.id)
    if annex is None:
        raise HTTPException(status_code=404, detail="Additional records not found")
    return s.EmployeeAdditionalRecordsPublic.model_validate(annex)


@employees_router.patch(
    "/{employee_id}/additional-records",
    response_model=s.EmployeeAdditionalRecordsPublic,
)
def update_additional_records(
    *, session: SessionDep, employee_id, body: s.EmployeeAdditionalRecordsUpdate,
    current_user: CurrentUser,
) -> Any:
    """Upsert a single employee's 201-file annex (ownership-checked)."""
    employee = _employee_or_404(session, employee_id)
    _ensure_annex_access(session, current_user, employee, elevated_action=PermissionAction.EDIT)
    annex = upsert_additional_records(session=session, employee_id=employee.id, data=body)
    return s.EmployeeAdditionalRecordsPublic.model_validate(annex)


@employees_router.get(
    "/{employee_id}/attachments",
    response_model=s.EmployeeAttachmentsList,
)
def list_attachments(
    session: SessionDep, employee_id, current_user: CurrentUser
) -> Any:
    """List an employee's uploaded documents (ownership-checked)."""
    employee = _employee_or_404(session, employee_id)
    _ensure_annex_access(session, current_user, employee, elevated_action=PermissionAction.VIEW)
    rows, count = get_attachments_for_employee(session=session, employee_id=employee.id)
    return s.EmployeeAttachmentsList(
        data=[s.EmployeeAttachmentsPublic.model_validate(r) for r in rows], count=count
    )


@employees_router.post(
    "/{employee_id}/attachments",
    response_model=s.EmployeeAttachmentsPublic,
    status_code=201,
)
def upload_attachment(
    *,
    session: SessionDep,
    employee_id,
    current_user: CurrentUser,
    file: UploadFile = File(...),
    type: str | None = Form(default=None),
    attachment_name: str | None = Form(default=None),
) -> Any:
    """Upload a document; the file is stored outside the web root, only its
    path is persisted on the DB row."""
    employee = _employee_or_404(session, employee_id)
    _ensure_annex_access(session, current_user, employee, elevated_action=PermissionAction.ADD)
    content = file.file.read()
    stored_path = store_attachment_file(
        employee_id=employee.id, filename=file.filename or "", content=content
    )
    db_obj = create_attachment(
        session=session,
        employee_id=employee.id,
        data=s.EmployeeAttachmentsCreate(
            type=type, attachment_name=attachment_name, original_file_name=file.filename
        ),
        file_path=stored_path,
        attachment_size=len(content),
    )
    return s.EmployeeAttachmentsPublic.model_validate(db_obj)


@employees_router.delete(
    "/{employee_id}/attachments/{attachment_id}",
    response_model=Message,
)
def delete_attachment(
    session: SessionDep, employee_id, attachment_id, current_user: CurrentUser
) -> Any:
    employee = _employee_or_404(session, employee_id)
    _ensure_annex_access(
        session, current_user, employee, elevated_action=PermissionAction.DELETE
    )
    attachment = get_attachment_by_id(session=session, attachment_id=attachment_id)
    if attachment is None or attachment.employee_id != employee.id:
        raise HTTPException(status_code=404, detail="Attachment not found")
    soft_delete_attachment(session=session, db_obj=attachment)
    return Message(message="Attachment deleted successfully")


# --- Divisions / Departments / Subdivisions / Positions ----------------------
divisions_router = _make_crud_router(
    prefix="/divisions",
    tag="divisions",
    module="division",
    model=m.Division,
    create=s.DivisionCreate,
    update=s.DivisionUpdate,
    public=s.DivisionPublic,
    listing=s.DivisionList,
    custom_delete=True,
)


@divisions_router.delete(
    "/{obj_id}",
    response_model=Message,
    dependencies=[Depends(require_permission("division", "delete"))],
)
def delete_division(session: SessionDep, obj_id) -> Any:
    """Q4: block deletion if active Departments reference the Division (409)."""
    db_obj = get_active_by_id(session=session, model=m.Division, obj_id=obj_id)
    if db_obj is None:
        raise HTTPException(status_code=404, detail="Division not found")
    active_departments = get_list(
        session=session, model=m.Department, filter_column=m.Department.division_id,
        filter_value=db_obj.id, limit=1,
    )[1]
    if active_departments > 0:
        raise HTTPException(
            status_code=409,
            detail="Division has active departments; cannot delete",
        )
    soft_delete_obj(session=session, db_obj=db_obj)
    return Message(message="Division deleted successfully")


departments_router = _make_crud_router(
    prefix="/departments",
    tag="departments",
    module="department",
    model=m.Department,
    create=s.DepartmentCreate,
    update=s.DepartmentUpdate,
    public=s.DepartmentPublic,
    listing=s.DepartmentList,
)

subdivisions_router = _make_crud_router(
    prefix="/subdivisions",
    tag="subdivisions",
    module="subdivision",
    model=m.Subdivision,
    create=s.SubdivisionCreate,
    update=s.SubdivisionUpdate,
    public=s.SubdivisionPublic,
    listing=s.SubdivisionList,
)

positions_router = _make_crud_router(
    prefix="/positions",
    tag="positions",
    module="emp_settings",
    model=m.Position,
    create=s.PositionCreate,
    update=s.PositionUpdate,
    public=s.PositionPublic,
    listing=s.PositionList,
)


# --- Project / ProjectType / Phase / Blocks / Lots ---------------------------
project_types_router = _make_crud_router(
    prefix="/project-types",
    tag="project_types",
    module="project_type",
    model=m.ProjectType,
    create=s.ProjectTypeCreate,
    update=s.ProjectTypeUpdate,
    public=s.ProjectTypePublic,
    listing=s.ProjectTypeList,
)

projects_router = _make_crud_router(
    prefix="/projects",
    tag="projects",
    module="projects",
    model=m.Project,
    create=s.ProjectCreate,
    update=s.ProjectUpdate,
    public=s.ProjectPublic,
    listing=s.ProjectList,
)

phases_router = _make_crud_router(
    prefix="/phases",
    tag="phases",
    module="phase",
    model=m.Phase,
    create=s.PhaseCreate,
    update=s.PhaseUpdate,
    public=s.PhasePublic,
    listing=s.PhaseList,
)

blocks_router = _make_crud_router(
    prefix="/blocks",
    tag="blocks",
    module="projects",
    model=m.Blocks,
    create=s.BlocksCreate,
    update=s.BlocksUpdate,
    public=s.BlocksPublic,
    listing=s.BlocksList,
    custom_delete=True,
)


@blocks_router.delete(
    "/{obj_id}",
    response_model=Message,
    dependencies=[Depends(require_permission("projects", "delete"))],
)
def delete_block(session: SessionDep, obj_id) -> Any:
    """Q7: 409 if an ACTIVE Category still references the Block."""
    db_obj = get_active_by_id(session=session, model=m.Blocks, obj_id=obj_id)
    if db_obj is None:
        raise HTTPException(status_code=404, detail="Block not found")
    if not ensure_not_referenced_by_active_category(session=session, blocks_id=db_obj.id):
        raise HTTPException(status_code=409, detail="Block is referenced by an active Category")
    soft_delete_obj(session=session, db_obj=db_obj)
    return Message(message="Block deleted successfully")


lots_router = _make_crud_router(
    prefix="/lots",
    tag="lots",
    module="projects",
    model=m.Lots,
    create=s.LotsCreate,
    update=s.LotsUpdate,
    public=s.LotsPublic,
    listing=s.LotsList,
    custom_delete=True,
)


@lots_router.delete(
    "/{obj_id}",
    response_model=Message,
    dependencies=[Depends(require_permission("projects", "delete"))],
)
def delete_lot(session: SessionDep, obj_id) -> Any:
    """Q7: 409 if an ACTIVE Category still references the Lot."""
    db_obj = get_active_by_id(session=session, model=m.Lots, obj_id=obj_id)
    if db_obj is None:
        raise HTTPException(status_code=404, detail="Lot not found")
    if not ensure_not_referenced_by_active_category(session=session, lot_id=db_obj.id):
        raise HTTPException(status_code=409, detail="Lot is referenced by an active Category")
    soft_delete_obj(session=session, db_obj=db_obj)
    return Message(message="Lot deleted successfully")


# --- Category / Model / ModelTypes / Owner -----------------------------------
categories_router = _make_crud_router(
    prefix="/categories",
    tag="categories",
    module="category",
    model=m.Category,
    create=s.CategoryCreate,
    update=s.CategoryUpdate,
    public=s.CategoryPublic,
    listing=s.CategoryList,
)

models_router = _make_crud_router(
    prefix="/models",
    tag="models",
    module="models",
    model=m.Model,
    create=s.ModelCreate,
    update=s.ModelUpdate,
    public=s.ModelPublic,
    listing=s.ModelList,
)

model_types_router = _make_crud_router(
    prefix="/model-types",
    tag="model_types",
    module="model_types",
    model=m.ModelTypes,
    create=s.ModelTypesCreate,
    update=s.ModelTypesUpdate,
    public=s.ModelTypesPublic,
    listing=s.ModelTypesList,
)

owners_router = _make_crud_router(
    prefix="/owners",
    tag="owners",
    module="owner",
    model=m.Owner,
    create=s.OwnerCreate,
    update=s.OwnerUpdate,
    public=s.OwnerPublic,
    listing=s.OwnerList,
)


@owners_router.get(
    "/{obj_id}/lot",
    response_model=s.CategoryPublic,
    dependencies=[Depends(require_permission("owner", "view"))],
)
def read_owner_lot_via_category(session: SessionDep, obj_id) -> Any:
    """Point 3: resolve the Lot an Owner holds THROUGH the Category record.

    ``Owner`` has no FK to Lots; the authoritative link is
    Owner <- Category.owner_id, Category.lot_id -> Lots.
    """
    owner = get_active_by_id(session=session, model=m.Owner, obj_id=obj_id)
    if owner is None:
        raise HTTPException(status_code=404, detail="Owner not found")
    categories, _ = get_list(
        session=session, model=m.Category,
        filter_column=m.Category.owner_id, filter_value=owner.id, limit=1,
    )
    if not categories:
        raise HTTPException(status_code=404, detail="Owner has no Category record")
    return s.CategoryPublic.model_validate(categories[0])


# --- EmployeeProjects / EmpTask ----------------------------------------------
employee_projects_router = _make_crud_router(
    prefix="/employee-projects",
    tag="employee_projects",
    module="emp_project",
    model=m.EmployeeProjects,
    create=s.EmployeeProjectsCreate,
    update=s.EmployeeProjectsUpdate,
    public=s.EmployeeProjectsPublic,
    listing=s.EmployeeProjectsList,
)


@employee_projects_router.post(
    "/{obj_id}/unassign",
    response_model=Message,
    dependencies=[Depends(require_permission("emp_project", "edit"))],
)
def unassign_employee_project(session: SessionDep, obj_id) -> Any:
    db_obj = get_active_by_id(session=session, model=m.EmployeeProjects, obj_id=obj_id)
    if db_obj is None:
        raise HTTPException(status_code=404, detail="EmployeeProject not found")
    db_obj.is_assigned = False
    session.add(db_obj)
    session.commit()
    session.refresh(db_obj)
    return Message(message="Employee unassigned from project")


emp_tasks_router = _make_crud_router(
    prefix="/emp-tasks",
    tag="emp_tasks",
    module="emp_task",
    model=m.EmpTask,
    create=s.EmpTaskCreate,
    update=s.EmpTaskUpdate,
    public=s.EmpTaskPublic,
    listing=s.EmpTaskList,
)


@emp_tasks_router.post(
    "/{obj_id}/approve",
    response_model=Message,
    dependencies=[Depends(require_permission("emp_project", "edit"))],
)
def approve_emp_task(session: SessionDep, obj_id) -> Any:
    """Q9: approve/deny gated under emp_project/edit, not emp_task."""
    db_obj = get_active_by_id(session=session, model=m.EmpTask, obj_id=obj_id)
    if db_obj is None:
        raise HTTPException(status_code=404, detail="EmpTask not found")
    db_obj.approved = True
    session.add(db_obj)
    session.commit()
    session.refresh(db_obj)
    return Message(message="EmpTask approved")


@emp_tasks_router.post(
    "/{obj_id}/deny",
    response_model=Message,
    dependencies=[Depends(require_permission("emp_project", "edit"))],
)
def deny_emp_task(session: SessionDep, obj_id) -> Any:
    db_obj = get_active_by_id(session=session, model=m.EmpTask, obj_id=obj_id)
    if db_obj is None:
        raise HTTPException(status_code=404, detail="EmpTask not found")
    db_obj.approved = False
    session.add(db_obj)
    session.commit()
    session.refresh(db_obj)
    return Message(message="EmpTask denied")


# Aggregate of every Phase 1 resource router.
routers: list[APIRouter] = [
    employees_router,
    divisions_router,
    departments_router,
    subdivisions_router,
    positions_router,
    project_types_router,
    projects_router,
    phases_router,
    blocks_router,
    lots_router,
    categories_router,
    models_router,
    model_types_router,
    owners_router,
    employee_projects_router,
    emp_tasks_router,
]
